export const games = [
    {
        title: "塞尔达传说",
        list: [
            {
                name: "塞尔达传说",
                enName: "The Legend of Zelda",
                logo: "Zelda/cover/TLoZ_Logo.png",
                year: 1986,
                isFull: false,
            },
            {
                name: "塞尔达传说2：林克的冒险",
                enName: "The Legend of Zelda2: The Adventure of Link",
                logo: "Zelda/cover/TAoL_Logo.png",
                year: 1987,
                isFull: false,
            },
            {
                name: "塞尔达传说：众神的三角力量",
                enName: "The Legend of Zelda: A Link to the Past",
                logo: "Zelda/cover/ALttP_Logo.png",
                year: 1991,
                isFull: false,
            },
            {
                name: "塞尔达传说：织梦岛",
                enName: "The Legend of Zelda: Link's Awakening",
                logo: "Zelda/cover/LA_Logo.png",
                year: 1993,
                isFull: false,
            },
            {
                name: "塞尔达传说：时之笛",
                enName: "The Legend of Zelda: Ocarina of Time",
                logo: "Zelda/cover/OoT_Logo.png",
                year: 1998,
                isFull: false,
            },
            {
                name: "塞尔达传说：姆吉拉的假面",
                enName: "The Legend of Zelda: Majora's Mask",
                logo: "Zelda/cover/MM_Logo.png",
                year: 2000,
                isFull: false,
            },
            {
                name: "塞尔达传说：不可思议的果实",
                enName: "The Legend of Zelda: Oracle of Seasons",
                logo: "Zelda/cover/OoS_Logo.png",
                year: 2002,
                isFull: false,
            },
            {
                name: "塞尔达传说：不可思议的果实",
                enName: "The Legend of Zelda: Oracle of Ages",
                logo: "Zelda/cover/OoA_Logo.png",
                year: 2002,
                isFull: false,
            },
            {
                name: "塞尔达传说：四支剑",
                enName: "The Legend of Zelda: Four Swords",
                logo: "Zelda/cover/FS_Logo.png",
                year: 2002,
                isFull: false,
            },
            {
                name: "塞尔达传说：风之杖",
                enName: "The Legend of Zelda: The Wind Waker",
                logo: "Zelda/cover/TWW_Logo.png",
                year: 2002,
                isFull: false,
            },
            {
                name: "塞尔达传说：四支剑大冒险",
                enName: "The Legend of Zelda: Four Swords Adventures",
                logo: "Zelda/cover/FSA_Logo.png",
                year: 2004,
                isFull: false,
            },
            {
                name: "塞尔达传说：缩小帽",
                enName: "The Legend of Zelda: The Minish Cap",
                logo: "Zelda/cover/TMC_Logo.png",
                year: 2006,
                isFull: false,
            },
            {
                name: "塞尔达传说：黄昏公主",
                enName: "The Legend of Zelda: Twilight Princess",
                logo: "Zelda/cover/TP_Logo.png",
                year: 2006,
                isFull: false,
            },
            {
                name: "塞尔达传说：幻影沙漏",
                enName: "The Legend of Zelda: Phantom Hourglass",
                logo: "Zelda/cover/PH_Logo.png",
                year: 2007,
                isFull: false,
            },
            {
                name: "塞尔达传说：灵魂轨迹",
                enName: "The Legend of Zelda: Spirit Tracks",
                logo: "Zelda/cover/ST_Logo.png",
                year: 2009,
                isFull: false,
            },
            {
                name: "塞尔达传说：天空之剑",
                enName: "The Legend of Zelda: Skyward Sword",
                logo: "Zelda/cover/SS_Logo.png",
                year: 2011,
                isFull: false,
            },
            {
                name: "塞尔达传说：众神的三角力量2",
                enName: "The Legend of Zelda: A Link Between Worlds",
                logo: "Zelda/cover/ALBW_Logo.png",
                year: 2013,
                isFull: false,
            },
            {
                name: "塞尔达传说：三角力量英雄",
                enName: "The Legend of Zelda: Tri Force Heroes",
                logo: "Zelda/cover/TFH_Logo.png",
                year: 2015,
                isFull: false,
            },
            {
                name: "塞尔达传说：荒野之息",
                enName: "The Legend of Zelda: Breath of the Wild",
                logo: "Zelda/cover/BoW_Logo.png",
                year: 2017,
                isFull: true,
            },
            {
                name: "塞尔达传说：王国之泪",
                enName: "The Legend of Zelda: Tears of the Kingdom",
                logo: "Zelda/cover/ToK_Logo.png",
                year: 2023,
                isFull: true,
            },
            {
                name: "塞尔达传说：智慧的再现",
                enName: "The Legend of Zelda: Echoes of Wisdom",
                logo: "Zelda/cover/EoW_logo.png",
                year: 2024,
                isFull: true,
            },
        ]
    },
    {
        title: "宝可梦",
        list: [],
    },
    {
        title: "怪物猎人",
        list: [],
    },
]