export const games = [
    {
        name: "塞尔达传说：荒野之息",
        enName: "The Legend of Zelda: Breath of the Wild",
        cover: "Legend_of_Zelda_Breath_of_the_Wild.jpg",
        category: 'NS',
        tags: ['塞尔达'],
        card: true,
        finish: true,
    },
    {
        name: "塞尔达传说：王国之泪",
        enName: "The Legend of Zelda: Tears of the Kingdom",
        cover: "Legend_of_Zelda_Tears_of_the_Kingdom.jpg",
        category: 'NS',
        tags: ['塞尔达'],
        card: true,
        finish: true,
    },
    {
        name: "塞尔达传说：天空之剑",
        enName: "The Legend of Zelda: Skyward Sword",
        cover: "Legend_of_Zelda_Skyward_Sword.jpg",
        category: 'NS',
        tags: ['塞尔达'],
        card: true,
        finish: true,
    },
    {
        name: "塞尔达传说：织梦岛",
        enName: "The Legend of Zelda: Link's Awakening",
        cover: "Legend_of_Zelda_links_awakening.jpg",
        category: 'NS',
        tags: ['塞尔达'],
        card: true,
        finish: true,
    },
    {
        name: "塞尔达传说：智慧的再现",
        enName: "The Legend of Zelda: Echoes of Wisdom",
        cover: "legend_of_zelda_echoes_of_wisdom.png",
        category: 'NS',
        tags: ['塞尔达'],
        card: true,
        finish: true,
    },
    {
        name: "塞尔达无双：灾厄启示录",
        enName: "Hyrule Warriors: Age of Calamity",
        cover: "Hyrule_Warriors_Age_of_Calamity.jpg",
        category: 'NS',
        tags: ['塞尔达'],
        card: true,
        finish: true,
    },
    {
        name: "塞尔达无双",
        enName: "Hyrule Warriors: Definitive Edition",
        cover: "Hyrule_Warriors_Definitive_Edition.jpg",
        category: 'NS',
        tags: ['塞尔达'],
        card: true,
        finish: false,
    },
    {
        name: "异度之刃",
        enName: "Xenoblade Chronicles: Definitive Edition",
        cover: "Xenoblade_Chronicles.png",
        category: 'NS',
        tags: ['异度'],
        card: true,
        finish: true,
    },
    {
        name: "异度之刃2",
        enName: "Xenoblade Chronicles2",
        cover: "Xenoblade_Chronicles_2.jpg",
        category: 'NS',
        tags: ['异度'],
        card: true,
        finish: true,
    },
    {
        name: "异度之刃3",
        enName: "Xenoblade Chronicles3",
        cover: "Xenoblade_Chronicles_3.png",
        category: 'NS',
        tags: ['异度'],
        card: true,
        finish: true,
    },
    {
        name: "动物森友会",
        enName: "Animal Crossing",
        cover: "Animal_Crossing.jpg",
        category: 'NS',
        tags: [],
        card: true,
        finish: true,
    },
    {
        name: "马力欧：奥德赛",
        cover: "Super_Mario_Odyssey.jpg",
        category: 'NS',
        tags: ['马力欧'],
        card: true,
        finish: true,
    },
    {
        name: "马力欧：惊奇",
        enName: "Super Mario Bros. Wonder",
        cover: "Super_Mario_Bros_Wonder.png",
        category: 'NS',
        tags: ['马力欧'],
        card: false,
        finish: false,
    },
    {
        name: "马力欧3D世界",
        cover: "super_mario_3d_world.jpg",
        category: 'NS',
        tags: ['马力欧'],
        card: false,
        finish: false,
    },
    {
        name: "纸片马力欧：折纸王国",
        cover: "paper_mario_the_origami_king.jpg",
        category: 'NS',
        tags: ['马力欧'],
        card: true,
        finish: true,
    },
    {
        name: "纸片马力欧：RPG",
        enName: "Paper Mario RPG",
        cover: "Paper_Mario_RPG.jpg",
        category: 'NS',
        tags: ['马力欧'],
        card: true,
        finish: false,
    },
    {
        name: "马力欧赛车8 豪华版",
        enName: "Mariokart 8 Deluxe",
        cover: "Mariokart_8_Deluxe.png",
        category: 'NS',
        tags: ['马力欧'],
        card: true,
        finish: false,
    },
    {
        name: "马力欧网球",
        enName: "Mario Tennis Ace",
        cover: "Mario_Tennis_Ace.jpg",
        category: 'NS',
        tags: ['马力欧'],
        card: true,
        finish: false,
    },
    {
        name: "宝可梦 Let's Go",
        enName: "Pokemon Let's Go",
        cover: "Pokemon_Lets_Go.png",
        category: 'NS',
        tags: ['宝可梦'],
        card: true,
        finish: false,
    },
    {
        name: "宝可梦：剑",
        enName: "Pokemon Sword",
        cover: "Pokemon_Sword.png",
        category: 'NS',
        tags: ['宝可梦'],
        card: true,
        finish: true,
    },
    {
        name: "宝可梦传说：阿尔宙斯",
        enName: "Pokemon Legends Arceus",
        cover: "Pokemon_Legends_Arceus.png",
        category: 'NS',
        tags: ['宝可梦'],
        card: true,
        finish: true,
    },
    {
        name: "怪物猎人GU",
        cover: "Monster_Hunter_GU.png",
        category: 'NS',
        tags: ['怪物猎人'],
        card: true,
        finish: false,
    },
    {
        name: "怪物猎人：Rise",
        cover: "Monster_Hunter_Rise.jpg",
        category: 'NS',
        tags: ['怪物猎人'],
        card: true,
        finish: true,
    },
    {
        name: "怪物猎人物语2",
        enName: "Monster Hunter Stories 2",
        cover: "Monster_Hunter_Stories_2.jpg",
        category: 'NS',
        tags: ['怪物猎人'],
        card: true,
        finish: false,
    },
    {
        name: "勇者斗恶龙 创世小玩家",
        cover: "dragon_quest_builders.jpg",
        category: 'NS',
        tags: ['勇者斗恶龙'],
        card: false,
        finish: true,
    },
    {
        name: "勇者斗恶龙 创世小玩家2",
        cover: "dragon_quest_builders_2.jpg",
        category: 'NS',
        tags: ['勇者斗恶龙'],
        card: false,
        finish: true,
    },
    {
        name: "勇者斗恶龙11",
        enName: "Dragon Quest 11",
        cover: "Dragon_Quest_11.jpg",
        category: 'NS',
        tags: ['勇者斗恶龙'],
        card: true,
        finish: false,
    },
    {
        name: "星之卡比 探索发现",
        cover: "Kirby_and_the_Forgotten_Land.jpg",
        category: 'NS',
        tags: ['卡比'],
        card: true,
        finish: false,
    },
    {
        name: "弥托邦",
        cover: "miitopia.jpg",
        category: 'NS',
        tags: [],
        card: true,
        finish: false,
    },
    {
        name: "女神异闻录5皇家版",
        cover: "persona_5_royal.jpg",
        category: 'NS',
        tags: [],
        card: true,
        finish: false,
    },
    {
        name: "小小梦魇",
        cover: "little_nightmares.jpg",
        category: 'NS',
        tags: [],
        card: true,
        finish: true,
    },
    {
        name: "小小梦魇2",
        cover: "little_nightmares_2.jpg",
        category: 'NS',
        tags: [],
        card: true,
        finish: true,
    },
    {
        name: "生化危机4",
        cover: "resident_evil_4.jpg",
        category: 'NS',
        tags: ['生化危机'],
        card: true,
        finish: false,
    },
    {
        name: "生化危机 启示录",
        cover: "resident_evil_revelations.png",
        category: 'NS',
        tags: ['生化危机'],
        card: true,
        finish: false,
    },
    {
        name: "战场女武神4",
        cover: "Valkyria_Chronicles_4.jpg",
        category: 'NS',
        tags: [],
        card: true,
        finish: false,
    },
    {
        name: "火炬之光2",
        cover: "torchlight_2.jpg",
        category: 'NS',
        tags: [],
        card: true,
        finish: false,
    },
    {
        name: "零：濡鸦巫女",
        cover: "zero.jpg",
        category: 'NS',
        tags: ["零"],
        card: true,
        finish: false,
    },
    {
        name: "天穗之咲稻姬",
        cover: "Sakuna.png",
        category: 'NS',
        tags: [],
        card: true,
        finish: false,
    },
    {
        name: "双点医院",
        cover: "two_point_hospital.png",
        category: 'NS',
        tags: [],
        card: true,
        finish: false,
    },
    {
        name: "雪地奔驰",
        cover: "snowrunner.jpg",
        category: 'NS',
        tags: [],
        card: true,
        finish: false,
    },
    {
        name: "世界游戏大全51",
        cover: "world_game_51.jpg",
        category: 'NS',
        tags: [],
        card: true,
        finish: true,
    },
    {
        name: "霍格沃兹之遗",
        cover: "harry_potter.jpg",
        category: 'NS',
        tags: [],
        card: true,
        finish: true,
    },
    {
        name: "胡闹厨房",
        cover: "overcooked.png",
        category: 'NS',
        tags: [],
        card: true,
        finish: false,
    },
    {
        name: "蜡笔小新 我与博士的暑假",
        cover: "la_bi_xiao_xin.png",
        category: 'NS',
        tags: [],
        card: true,
        finish: false,
    },
    {
        name: "乐高世界",
        cover: "lego_world.png",
        category: 'NS',
        tags: [],
        card: true,
        finish: false,
    },
    {
        name: "健身环大冒险",
        cover: "Ring_Fit_Adventure.jpg",
        category: 'NS',
        tags: [],
        card: true,
        finish: false,
    },
    {
        name: "Nintendo Switch Sports",
        cover: "Nintendo_Switch_Sports.jpg",
        category: 'NS',
        tags: [],
        card: false,
        finish: true,
    },
    {
        name: "猎天使魔女2",
        cover: "Bayonetta2.jpg",
        category: 'NS',
        tags: [],
        card: false,
        finish: false,
    },
    {
        name: "潜水员戴夫",
        cover: "dave.jpg",
        category: 'NS',
        tags: [],
        card: true,
        finish: false,
    },
]